[package]
name = "new-peak-wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
chia = "0.13.0"
chia-wallet-sdk = { version = "0.14.0" }
tokio = { version = "1.40.0", features = ["full"] }
